import { CKCRequest } from '@/lib/definitions';
import { subDays } from 'date-fns';

// This is now just used for the "Pending" tab, which is a mock.
// The "Accepted" tab uses live data from Firestore.
export const mockRequests: CKCRequest[] = [
  {
    id: 'REQ001',
    companyId: 'COMP001',
    companyName: 'Reliance Industries',
    financialInputSector: 'Energy',
    listed: 'Yes',
    rating: 'AAA',
    hoRoName: 'John Doe',
    dealingAnalyst: 'Jane Smith',
    groupHead: 'Peter Jones',
    assignedTo: null,
    checker: 'Admin',
    status: 'PENDING',
    cycle: 'Surveillance',
    auditedFY: ['2023'],
    provisionalFY: [],
    projectionFY: [],
    remarks: 'Standard surveillance.',
    receiptDateTime: subDays(new Date(), 2),
    receiptResponseDateTime: null,
    entryAllottedDateTime: null,
    entryCompletedDateTime: null,
    checkingAllottedDateTime: null,
    checkingCompletedDateTime: null,
    sentBackFlag: false,
    createdBy: 'System',
    overallStatus: 'Pending',
    itemType: 'Operational',
    path: '/requests/1',
    resultType: 'Consolidated',
  },
  {
    id: 'REQ002',
    companyId: 'COMP002',
    companyName: 'Tata Consultancy Services',
    financialInputSector: 'IT',
    listed: 'Yes',
    rating: 'AA+',
    hoRoName: 'John Doe',
    dealingAnalyst: 'Emily White',
    groupHead: 'Peter Jones',
    assignedTo: null,
    checker: 'Admin',
    status: 'PENDING',
    cycle: 'Initial',
    auditedFY: ['2022', '2023'],
    provisionalFY: [],
    projectionFY: [],
    remarks: 'New client initial rating.',
    receiptDateTime: subDays(new Date(), 1),
    receiptResponseDateTime: null,
    entryAllottedDateTime: null,
    entryCompletedDateTime: null,
    checkingAllottedDateTime: null,
    checkingCompletedDateTime: null,
    sentBackFlag: false,
    createdBy: 'System',
    overallStatus: 'Pending',
    itemType: 'Operational',
    path: '/requests/2',
    resultType: 'Standalone',
  },
  {
    id: 'REQ003',
    companyId: 'COMP003',
    companyName: 'HDFC Bank',
    financialInputSector: 'Banking',
    listed: 'Yes',
    rating: 'AAA',
    hoRoName: 'John Doe',
    dealingAnalyst: 'Michael Green',
    groupHead: 'Peter Jones',
    assignedTo: null,
    checker: 'Admin',
    status: 'PENDING',
    cycle: 'Surveillance',
    auditedFY: ['2023'],
    provisionalFY: [],
    projectionFY: [],
    remarks: 'Quarterly review.',
    receiptDateTime: subDays(new Date(), 5),
    receiptResponseDateTime: null,
    entryAllottedDateTime: null,
    entryCompletedDateTime: null,
    checkingAllottedDateTime: null,
    checkingCompletedDateTime: null,
    sentBackFlag: false,
    createdBy: 'System',
    overallStatus: 'Pending',
    itemType: 'Operational',
    path: '/requests/3',
    resultType: 'Consolidated',
  },
  {
    id: 'REQ004',
    companyId: 'COMP004',
    companyName: 'Infosys',
    financialInputSector: 'IT',
    listed: 'Yes',
    rating: 'AA+',
    hoRoName: 'John Doe',
    dealingAnalyst: 'Jane Smith',
    groupHead: 'Peter Jones',
    assignedTo: null,
    checker: 'Admin',
    status: 'PENDING',
    cycle: 'Surveillance',
    auditedFY: ['2023'],
    provisionalFY: [],
    projectionFY: [],
    remarks: '',
    receiptDateTime: subDays(new Date(), 3),
    receiptResponseDateTime: null,
    entryAllottedDateTime: null,
    entryCompletedDateTime: null,
    checkingAllottedDateTime: null,
    checkingCompletedDateTime: null,
    sentBackFlag: false,
    createdBy: 'System',
    overallStatus: 'Pending',
    itemType: 'Operational',
    path: '/requests/4',
    resultType: 'Standalone',
  },
  {
    id: 'REQ005',
    companyId: 'COMP005',
    companyName: 'Future Retail',
    financialInputSector: 'Retail',
    listed: 'No',
    rating: 'B',
    hoRoName: 'John Doe',
    dealingAnalyst: 'Emily White',
    groupHead: 'Peter Jones',
    assignedTo: null,
    checker: 'Admin',
    status: 'PENDING',
    cycle: 'Initial',
    auditedFY: ['2021', '2022'],
    provisionalFY: [],
    projectionFY: [],
    remarks: 'High-risk initial assessment.',
    receiptDateTime: subDays(new Date(), 10),
    receiptResponseDateTime: null,
    entryAllottedDateTime: null,
    entryCompletedDateTime: null,
    checkingAllottedDateTime: null,
    checkingCompletedDateTime: null,
    sentBackFlag: true,
    createdBy: 'System',
    overallStatus: 'Pending',
    itemType: 'Operational',
    path: '/requests/5',
    resultType: 'Standalone',
  },
  ...Array.from({ length: 25 }, (_, i) => ({
    id: `REQ${String(i + 6).padStart(3, '0')}`,
    companyId: `COMP${String(i + 6).padStart(3, '0')}`,
    companyName: `Generic Corp ${i + 1}`,
    financialInputSector: 'Miscellaneous',
    listed: i % 2 === 0 ? ('Yes' as const) : ('No' as const),
    rating: 'A',
    hoRoName: 'John Doe',
    dealingAnalyst: 'Chris Brown',
    groupHead: 'Peter Jones',
    assignedTo: null,
    checker: 'Admin',
    status: 'PENDING' as const,
    cycle: i % 3 === 0 ? ('Initial' as const) : ('Surveillance' as const),
    auditedFY: ['2023'],
    provisionalFY: [],
    projectionFY: [],
    remarks: `Auto-generated request ${i + 1}.`,
    receiptDateTime: subDays(new Date(), i + 1),
    receiptResponseDateTime: null,
    entryAllottedDateTime: null,
    entryCompletedDateTime: null,
    checkingAllottedDateTime: null,
    checkingCompletedDateTime: null,
    sentBackFlag: false,
    createdBy: 'System',
    overallStatus: 'Pending',
    itemType: 'Operational',
    path: `/requests/${i + 6}`,
    resultType: 'Consolidated' as const,
  })),
];
