export type CKCRequest = {
  id: string;
  companyId: string;
  companyName: string;
  financialInputSector: string;
  listed: 'Yes' | 'No';
  rating: string;
  hoRoName: string;
  dealingAnalyst: string;
  groupHead: string;
  assignedTo: string | null;
  checker: string;
  status: 'PENDING' | 'ACCEPTED' | 'CLOSED';
  cycle: 'Initial' | 'Surveillance';
  auditedFY: string[];
  provisionalFY: string[];
  projectionFY: string[];
  remarks: string;
  receiptDateTime: Date;
  receiptResponseDateTime: Date | null;
  entryAllottedDateTime: Date | null;
  entryCompletedDateTime: Date | null;
  checkingAllottedDateTime: Date | null;
  checkingCompletedDateTime: Date | null;
  sentBackFlag: boolean;
  createdBy: string;
  overallStatus: string;
  itemType: string;
  path: string;
  resultType: 'Standalone' | 'Consolidated';
};
